markdown: rdiscount
permalink: /:title/
url: http://qijun.info
name: 点滴
author: qijun
qq: 875436837
email: qijunnewan@gmail.com
duoshuo: qijun
cnzz: 1000419679
weibo: weijue@live.com
github: qijun
pygments: true
safe: false
paginate: 20
about: "这里是 qijun 的个人博客，创建于 2013 年,2014年开始使用，准备长期在此折腾；@ GitHub。<br /><br />这里包含了部分个人的“折腾”过程、结论和成果，切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
